export { default as SvgCall } from './Call'
export { default as SvgMarker } from './Marker'
export { default as SvgComment } from './Comment'
export { default as SvgEnvelop} from './Envelop'
export { default as SvgFacebook } from './Facebook'
export { default as SvgInstagram } from './Instagram'
export { default as SvgPhone } from './Phone'
export { default as SvgPinterest} from './Pinterest'
export { default as SvgRepeat } from './Repeat'
export { default as SvgRocket} from './Rocket'
export { default as SvgTag } from './Tag'
export { default as SvgTwitter } from './Twitter'
export { default as SvgWallet} from './Wallet'
export { default as SvgYoutube } from './Youtube'