export { default as Diversity } from './Diversity'
export { default as Efficiency } from './Efficiency'
export { default as Excellence } from './Excellence'
export { default as Integrity } from './Integrity'
export { default as Leader } from './Leader'
export { default as Philarthropy } from './Philarthropy'
export { default as Quality } from './Quality'
export { default as Trust } from './Trust'